[[main]]
    identifier = "about"
    name = "About me"
    url = "/"
    weight = 1

[[main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts"
    weight = 2

[[main]]
    identifier = "poetry"
    name = "Poetry"
    url = "/poetry"
    weight = 3

[[main]]
    identifier = "act"
    name = "Act"
    url = "/act"
    weight = 4

    
# Social Media Configuration

[[social]]
    identifier = "instagram"
    name = "Instagram"
    url = "https://www.instagram.com/b_aldo/"
    weight = 1

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/alduxx"
    weight = 2